% Code generated by Anna Cassidy (with some help from ChatGPT) 05/23/2024
% Last edited by AC on 01/28/2026

%% Functions (if they have been changed or updated (ie different function name), then they need to be updated below
% CometAnalysis_Align_20240709(pathtofile,outputfoldersuffix,filename,windowsize,pospix,timepix)
% CometAnalysis_SubtractBGFixedPixel_20240709(foldername,solpix,latpix)
% CometAnalysis_ExponentialFitAverageLinescan_20250115_yOffset(path,subfolder,filename,outputfilename,fitstartpix,fitendpix)

%% Before proceeding, the following must be updated:
% base folder directory (base_dir)
% datasets = {folder within the directory, output folder suffix, points file name}
% align_params = {windowsize,pospix,timepix}
% bg_subtract_params = {solpix, latpix}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Set up the base directory
base_dir = "C:\Users\annao\OneDrive - Vanderbilt\Desktop\To_be_analyzed\VF MCAK Data from 2019";

% Define datasets to be processed
% datasets = {folder within the directory, output folder suffix, points file name}
datasets = {
    {'20uMT_200nMEB1GFP_100nMMCAK_3.13nMXMAP_XB_001\RESULTS', '4s_1', 'Points_file_4sORmore.xlsx'}; %% 0.2041  (VF MCAK Data from 2019)
    {'20uMT_200nMEB1GFP_100nMMCAK_XB_002\RESULTS', '4s_2', 'Points_file_4sORmore.xlsx'}; %% 0.2031  (VF MCAK Data from 2019)
    {'20uMT_200nMEB1GFP_200nMMCAK_25nMXMAP215_XB_003\RESULTS', '4s_3', 'Points_file_4sORmore.xlsx'}; %% 0.2039  (VF MCAK Data from 2019)
    {'20uMT_200nMEB1GFP_MB_25nMXMAP_XB_002\RESULTS', '4s_2', 'Points_file_4sORmore.xlsx'}; %% 0.2031  (VF MCAK Data from 2019)
};

% Parameters for alignment and background subtraction
% align_params = {windowsize,pospix,timepix}
% do not change windowsize = 5
%% SDC pixel size 110 nm at 5 frames/s (0.2 s/frame)
%%CISR X1 SDC pixel size 90.19 nm with variable frame rates
align_params = {5, 158.3, 0.2038}; 
% bg_subtract_params = {solpix, latpix}
bg_subtract_params = {30, 50};

% Perform alignment for each dataset
for i = 1:length(datasets)
    disp(['Processing dataset ' num2str(i) ' of ' num2str(length(datasets))]);  % Debug output

    data = datasets{i};
    date = data{1};  % Extract the date
    sample = data{2};  % Extract the sample name
    points_file = data{3};  % Extract the points file name
    
    % Construct the full file path for the points file
    points_file_path = fullfile(base_dir, date, points_file);
    
    % Check if the file exists at the constructed path
    if exist(points_file_path, 'file') == 2
        % If the file exists, perform the alignment
        disp(['Aligning dataset: ' points_file]);  % Debug output
        CometAnalysis_Align_20240709(fullfile(base_dir, date), sample, points_file, align_params{:});
    else
        % If the file doesn't exist, display an error message
        disp(['Error: Points file not found: ' points_file_path]);  % Debug output
    end
end


% Perform background subtraction for each dataset
for i = 1:length(datasets)
    data = datasets{i};
    date = data{1};
    sample = data{2};
    foldername = fullfile(base_dir, date, ['individualLS_', sample]);
    CometAnalysis_SubtractBGFixedPixel_20240709(foldername, bg_subtract_params{:});
end


% Perform exponential fit analysis for each dataset
for i = 1:length(datasets)
    data = datasets{i};
    date = data{1};  % The date of the dataset (e.g., '20211116')
    sample = data{2};  % The sample name (e.g., '5s_Cells')

    % Create the full folder path for the dataset
    this_folder = fullfile(base_dir, date, ['individualLS_', sample]);

    % Get the list of files to process (files with '-Average.dat' extension)
    filesInFolder = dir(fullfile(this_folder, '*-Average.dat'));
    NumofFiles = numel(filesInFolder);

    % Perform exponential fit analysis on each file found in the folder
    for ii = 1:NumofFiles
        close all  % Close any existing figures
        iiname = filesInFolder(ii).name;  % Get the file name (e.g., 'K0119-BGsubstracted-Average.dat')
        
        % Define the output filename based on the sample
        fit_filename = sprintf('Fit_p1-25_%s', sample);  % Example: 'Fit_p1-25_5s_Cells'
        
        % Call the function to perform the exponential fit analysis
        CometAnalysis_ExponentialFitAverageLinescan_20250115_yOffset(...
            this_folder, ...   % Path to the folder containing the file
            '', ...            % Empty string since we're passing the full path already
            iiname, ...        % Name of the current file
            fit_filename, ...  % Output filename
            1, ...             % Parameter for fitting (e.g., starting frame)
            25 ...             % Parameter for fitting (e.g., number of frames)
        );
    end
end
