//Code generated by Anna Cassidy (with some help from ChatGPT) 04/09/20205
//Last edited by AC on 01/28/2026

// Full Integrated Code
// Before beginning, open the image that you plan to analyze. Then run this code. 
// You should not have to manually change anything in this code.
//Full directions can be found in the ReadMe document

////////////////////////////////////////////////////////////////////////////////////

// Step 1: Identifies image and image directory and then defines and creates output folders
imagePath = getInfo("image.directory"); // Get the path of the last opened image
imageName = getTitle(); // Get the name of the last opened image

// Ensure an image is open
if (imagePath == "" || imageName == "") { 
    print("No image is currently open. Please open an image first.");
    exit();
}

// Remove the file extension from the image name
imageBaseName = substring(imageName, 0, lastIndexOf(imageName, ".")); 
// Create a new output folder based on the image name
outputMASTER = imagePath + imageBaseName + File.separator;

// Check if the folder exists; if not, create it
if (!File.isDirectory(outputMASTER)) {
    File.makeDirectory(outputMASTER);
}

// Print confirmation
print("outputMASTER folder created: " + outputMASTER); 

// Create a subfolder within the output folder
output = outputMASTER + "RESULTS" + File.separator; 

// Check if the subfolder exists, if not, create it
if (!File.isDirectory(output)) {
    File.makeDirectory(output);
}

print("output folder created: " + output); // Print confirmation

////////////////////////////////////////////////////////////////////////////////////

// Step 2: Get the title of the current image and process the channels
fullFilename = getTitle(); // Get the title of the current image
filename = fullFilename.replace(".nd2", ""); // Remove the .nd2 extension

selectImage(fullFilename); // Select the input image

// Extract Metadata///////////////////////////////////////////////////////
//output = getInfo("image.directory");
// Retrieve the metadata string
metadata = getMetadata("Info");
if (metadata == "" || metadata == "") {
    metadata = getMetadata("");
}

// Print raw metadata for debugging
//print("Raw Metadata: \n" + metadata);

// Check if metadata is available
if (metadata == "") {
    print("Error: No metadata found. Ensure the file has metadata or is opened correctly.");
    exit();
}

// Extract SizeT (Number of Frames)
sizeT = extractNumber("SizeT =", metadata);
totalFramesText = "Total Frames: " + sizeT;
print("Total Frames: " + sizeT);

// Extract Total Imaging Duration from last timestamp
totalTime = extractNumber("timestamp #" + sizeT + " =", metadata);
totalTimeText = "Total Imaging Duration: " + totalTime + " seconds";
print("Total Imaging Duration: " + totalTime + " seconds");

// Calculate Frame Rate (FPS)
if (sizeT > 0 && totalTime > 0) {
    fps = totalTime / sizeT;
    frameRateText = "Frame Rate: " + fps + " s/frame";
    print("Frame Rate: " + fps + " s/frame");
} else {
    print("Frame Rate: Could not be determined");
}

// Extract Pixel Size
pixelSize = extractNumber("dCalibration =", metadata);
pixelSizeText = "Pixel Size: " + pixelSize + " µm/pixel";
print("Pixel Size: " + pixelSize + " µm/pixel");

// Function to extract numerical values from metadata
function extractNumber(key, text) {
    index = indexOf(text, key);
    if (index == -1) return -1;
    subtext = substring(text, index + lengthOf(key));
    return parseFloat(substring(subtext, 0, indexOf(subtext, "\n")));
}

// Define output file path
outputFile = imagePath + "Imaging specs.txt";

// Write metadata to file
fileContent = "\n---------------------------\n" + filename + "\n" + totalFramesText + "\n" + totalTimeText + "\n" + frameRateText + "\n" + pixelSizeText;
File.append(fileContent, outputFile);

print("Metadata saved to: " + outputFile);

//////////////////////////////////////////////////////////////////
selectImage(fullFilename); // Select the input image
run("Split Channels"); // Split the channels into C1, C2

// Handle Channel 1 (C1)
selectWindow("C1-" + fullFilename);
run("Enhance Contrast", "saturated=0.35");
saveAs("Tiff", outputMASTER + "C1-" + filename + ".tif");
close();

// Handle Channel 2 (C2)
selectWindow("C2-" + fullFilename);
run("Enhance Contrast", "saturated=0.35");
saveAs("Tiff", outputMASTER + "C2-" + filename + ".tif");

TiffFilename = filename + ".tif";
//open(imagePath + "Merged-1frame_" + TiffFilename + ".tif");

// Apply Z-Projection on Channel 2 (MAX Image)
selectWindow("C2-" + TiffFilename); // Ensure the original image is selected before Z-Projection
var frameCount = nSlices; // Retrieves the total number of slices in the current stack
run("Z Project...", "projection=[Max Intensity]");
selectWindow("C2-" + TiffFilename); // Ensure the original image is selected before Z-Projection
run("Temporal-Color Code", "lut=Fire start=" + start + " end=" + frameCount + " create");
// Define parameters

var batchSize = 60; // Frames per batch

// Calculate the number of full batches
var fullBatches = Math.floor(frameCount / batchSize);
var remainder = frameCount % batchSize;

// Loop through full batches
for (var batch = 0; batch < fullBatches; batch++) {
    var start = batch * batchSize + 1; // Start frame (1-indexed)
    var end = start + batchSize - 1; // End frame
    processFrames(TiffFilename, start, end);
}

// Handle the remainder (if any)
if (remainder > 0) {
    var start = fullBatches * batchSize + 1;
    var end = frameCount;
    processFrames(TiffFilename, start, end);
}

// Function to process frames
function processFrames(filename, start, end) {
    // Select the window
    selectWindow("C2-" + filename);
    // Run the Temporal-Color Code with specified start and end
    run("Temporal-Color Code", "lut=Fire start=" + start + " end=" + end + " create");
}

// Reset the ROI Manager (optional, clear any previous ROIs)
//roiManager("reset");
//print("ROI manager reset");

// User adds ROIs (for manual interaction)
//setTool("rectangle");
//waitForUser("Draw and add ROIs around each visible comet in the original image, then press OK.");
//print("ROIs drawn");

// User adds ROIs (for manual interaction)
setTool("polyline");
waitForUser("Draw ROI line along each identified cleanish comet, \n" +
			"then press OK.");
print("ROIs drawn");

// Save the entire ROI set with the naming pattern "ROIset-" + filename + ".roi"
roiFilename = "ROIset-" + filename + ".zip";  // Create the ROI file name
print(roiFilename);  // Print the file name for debugging
roiManager("Save", outputMASTER + "\\" + roiFilename);  // Save the ROIs (use "\\" for Windows paths)
print("ROIset saved");

////////////////////////////////////////////////////////////////////////////////////

// Step 3: Switch back to the original image (C2) for comet identification, ROI drawing, and crop generation
selectWindow("C2-" + TiffFilename); // Switch back to the original image (C2) after Z-Projection
print("Selected " + TiffFilename);
fullFilename = getTitle(); // Get the title of the current image (Max Intensity projection)
filename = fullFilename.replace(".tif", ""); // Remove the .tif extension
run("Close All");
print("All closed");
//waitForUser("Is everything closed?");

run("Collect Garbage");
wait(500);

// Generate Kymographs for each ROI
function kymos(fullFilename, output, index) {
    print("File path location: " + outputMASTER + fullFilename); 
    open(outputMASTER + fullFilename);
    selectWindow(fullFilename);
    print("Opened: " + getTitle());
    roiManager("select", index);
    print("Generating kymograph " + index + " of " + n-1);
    run("Multi Kymograph", "linewidth=1");
    saveAs("Tiff", output + fullFilename.replace(".tif", "-") + index + "K.tif"); // K.tif file generation
    print("Kymograph saved: " + output + fullFilename.replace(".tif", "-") + index + "K.tif");
    close();
}

setBatchMode(true);


// Check the number of ROIs
var n = roiManager("count");
if (n == 0) {
    print("Error: No ROIs found. Please draw some crops.");
    exit();
}

// Calculate the number of full batches and remainder
var batchSize = 5; //batch handle in increment #
var fullBatches = Math.floor(n / batchSize);
var remainder = n % batchSize;

// Loop through full batches
for (var batch = 0; batch < fullBatches; batch++) {
    var start = batch * batchSize;
    var end = start + batchSize;
    
    for (var index = start; index < end; index++) {
        kymos(fullFilename, output, index);
        selectWindow(fullFilename);
    }
    
    setBatchMode(false);
    run("Collect Garbage");
    //wait(500);
    setBatchMode(true);
}

// Handle the remainder (if any)
if (remainder > 0) {
    var start = fullBatches * batchSize;
    var end = n;
    
    for (var index = start; index < end; index++) {
        kymos(fullFilename, output, index);
        selectWindow(fullFilename);
    }
    
    setBatchMode(false);
    run("Collect Garbage");
    //wait(500);
}


// Close all open images and clear the ROI manager
run("Close All"); 

// Reset the ROI Manager (optional, clear any previous ROIs)
roiManager("reset");
print("ROI manager reset");

////////////////////////////////////////////////////////////////////////////////////

// Step 4: Get list of cropped TIFF files
//Debug
//print(imagePath);
//print(imageName);
//print(imageBaseName);
//print(outputMASTER);
//print(output);
//print(fullFilename);
//print(filename);
run("Collect Garbage");

// Debug message to confirm the path
print("Getting kymograph files from directory: " + output);  

// Debugging: Confirm output directory
print("Output directory: " + output);

// Ensure the output path is correctly set
if (!File.isDirectory(output)) {
    print("Error: Output folder not found at path: " + output);
    exit();
}

// List files in the output directory
print("Fetching files from output directory: " + output);
files = getFileList(output);

print("Files found in directory:");
for (var i = 0; i < files.length; i++) {
    print(files[i]);
}

// Check if files exist
if (files.length == 0) {
    print("Error: No files found in the directory.");
    exit();
}

// Filter out the cropped TIFF files by checking for the naming pattern "-#K.tif"
var KYMOFiles = newArray();
for (var i = 0; i < files.length; i++) {
    // Check if the file name matches the pattern "-X.tif" where X is any digit
    if (files[i].matches(".*-\\d+K\\.tif$")){
        KYMOFiles[KYMOFiles.length] = files[i];
    }
}

// Debugging: Output cropped files
print("Filtered kymograph files:");
for (var i = 0; i < KYMOFiles.length; i++) {
    print(KYMOFiles[i]);
}

// Check if any cropped files were found
if (KYMOFiles.length == 0) {
    print("Error: No kymograph files found.");
    exit();
}

run("Collect Garbage");

////////////////////////////////////////////////////////////////////////////////////
// Step 5: Create the points files
// Identify kymograph files to be processed
print("Kymograph files to process:");
for (i = 0; i < KYMOFiles.length; i++) {
    print(KYMOFiles[i]);  // This will print each file name in the array
}

print("Processing kymograph files...");
var allPointData = "";

// This loop will process all identified kymograph files
// Prompts point selection (Kp.tif file)
// Loop will complete processing of each video individually
// Loop through the kymograph files
for (i = 0; i < KYMOFiles.length; i++) {
    print("Processing file " + (i + 1) + " of " + KYMOFiles.length);
    currentFile = KYMOFiles[i];
    print("Attempting to open file: " + output + currentFile);
    
    if (!File.exists(output + currentFile)) {
        print("Error: File not found - " + output + currentFile);
        continue; // Skip to the next file
    }

    // Open the file with error handling
    setBatchMode(false); // Disable batch mode for visibility
    wait(500); // Ensure file is ready to be accessed
    open(output + currentFile);
	//run("In [+]");
	run("In [+]");
	run("In [+]");
    kymoFilename = getTitle();
    print("Kymograph created: " + kymoFilename);

    selectImage(kymoFilename);
    setTool("multipoint");
    waitForUser("Identify growth events that visually appear \n" +
    			" to have a constant slope. Click the start and \n" +
                "end points of constant slope regions using the \n" +
                "multipoint tool, then press OK.");
    saveAs("Tiff", output + kymoFilename.replace(".tif", "") + "p.tif");
    
    
	// Initialize coordinate arrays
	var xpoints = newArray();
	var ypoints = newArray();
	getSelectionCoordinates(xpoints, ypoints); // Populate arrays with selection coordinates
	
	// Debugging: Check if points are captured
	print("Kymograph filename: " + kymoFilename);
	print("Number of X points: " + xpoints.length);
	print("Number of Y points: " + ypoints.length);
	
	// Ensure points are selected
	if (xpoints.length == 0 || ypoints.length == 0) {
	    print("Error: No points selected. Please select points on the kymograph and try again.");
	    exit(); // Stop execution
	}
	
	// Initialize pair number
	var pairNumber = 1;
	
	// Loop through the points and print in the desired format
	for (var p = 0; p < xpoints.length; p += 2) {
	    // Print the filename and first pair of coordinates
	    print(kymoFilename + "\t" + pairNumber + "\t" + xpoints[p] + "\t" + ypoints[p]);
		allPointData += kymoFilename + "\t" + pairNumber + "\t" + xpoints[p] + "\t" + ypoints[p] + "\n";
        
	    // Row 2: Indent and print the second set of coordinates if exists
	    if (p + 1 < xpoints.length) {
	        print("\t" + pairNumber + "\t" + xpoints[p + 1] + "\t" + ypoints[p + 1]);
	        allPointData += "\t" + pairNumber + "\t" + xpoints[p + 1] + "\t" + ypoints[p + 1] + "\n";
	    }
	
	    // Increment pair number after every two rows
	    pairNumber++;
	    
		print("Finished comet:" + kymoFilename);
			
    }

    
    // Close the file and free memory
    run("Close All");
    print("File processed and closed: " + kymoFilename);
    run("Collect Garbage");
    print("Start processing file " + (i+1) + " of " + KYMOFiles.length);

}

////////////////////////////////////////////////////////////////////////////////////

print("Processing complete.");
print(allPointData);
File.saveString(allPointData, output + "AllPointsData.txt");
